---
# Homepage configuration
# See https://fontawesome.com/v5/search for icons options

title: "Dante's Homeserver"
subtitle: "danteb.com"
logo: "logo.png"
# icon: "fas fa-skull-crossbones" # Optional icon

header: true
# footer: '<p>Created with <a href="https://github.com/bastienwirtz/homer">Homer</a>.</p>' # set false if you want to hide it.
footer: false # set false if you want to hide it.

columns: "auto" # "auto" or number (must be a factor of 12: 1, 2, 3, 4, 6, 12)
connectivityCheck: true # whether you want to display a message when the apps are not accessible anymore (VPN disconnected for example).

# Set the default layout and color scheme
defaults:
  layout: columns # Either 'columns', or 'list'
  colorTheme: auto # One of 'auto', 'light', or 'dark'

# Optional theme customization
theme: default
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link: "#3273dc"
    link-hover: "#363636"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#3273dc"
    link-hover: "#ffdd57"

# Optional message
message:
  # url: https://github.com/dantebarbieri/homeserver-homer
  #   style: "is-dark" # See https://bulma.io/documentation/components/message/#colors for styling options.
  title: "Homer Homepage"
  icon: "fa fa-home"
  content: "This homepage uses <a href='https://github.com/bastienwirtz/homer'>Homer</a> to display all the services running on my home server. You can find the source code on <a href='https://github.com/dantebarbieri/homeserver-homer'>GitHub</a>."

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  - name: "Home"
    icon: "fas fa-home"
    url: "#"
  - name: "Docker"
    icon: "fab fa-docker"
    url: "https://github.com/dantebarbieri/homeserver-docker"
    target: "_blank" # optional html a tag target attribute
  - name: "NixOS"
    icon: "fab fa-linux"
    url: "https://github.com/dantebarbieri/homeserver-nixos"
    target: "_blank" # optional html a tag target attribute
  #   - name: "Wiki"
  #     icon: "fas fa-book"
  #     url: "https://www.wikipedia.org/"
  #   # this will link to a second homer page that will load config from additional-page.yml and keep default config values as in config.yml file
  #   # see url field and assets/additional-page.yml.dist used in this example:
  - name: "Management"
    icon: "fas fa-file-alt"
    url: "#management"

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Game Servers"
    icon: "fas fa-server"
    items:
      - name: "Hardcore Minecraft"
        logo: "assets/tools/hardcore_logo.png"
        subtitle: "mc.danteb.com"
        tag: "server"
        keywords: "game mc minecraft"
        url: "https://mcsrvstat.us/server/mc.danteb.com"
        target: "_blank" # optional html a tag target attribute
      - name: "RL Craft Minecraft"
        logo: "https://media.forgecdn.net/avatars/thumbnails/468/243/64/64/637751369169569212.png"
        subtitle: "rlcraft.danteb.com"
        tag: "server"
        keywords: "game mc minecraft"
        url: "https://mcsrvstat.us/server/rlcraft.danteb.com"
        target: "_blank" # optional html a tag target attribute
      - name: "Hytale"
        logo: "assets/tools/hytale_logo.png"
        subtitle: "danteb.com:5205"
        tag: "server"
        keywords: "game hytale"
        url: "https://hytale-servers.com/server/dante-s-hytale-server"
        target: "_blank" # optional html a tag target attribute
      - name: "Satisfactory"
        logo: "assets/tools/satisfactory_logo.png"
        subtitle: "danteb.com:7778"
        tag: "server"
        keywords: "game satisfactory factory"
        url: "https://store.steampowered.com/app/526870/Satisfactory/"
        target: "_blank" # optional html a tag target attribute
  - name: "Media"
    icon: "fas fa-tv"
    items:
      - name: "Plex"
        logo: "assets/homer-icons/svg/plex.svg"
        subtitle: "Movies & TV"
        tag: "remote app"
        keywords: "media"
        url: "https://plex.danteb.com"
        target: "_blank" # optional html a tag target attribute
      - name: "Jellyfin"
        logo: "assets/homer-icons/svg/jellyfin.svg"
        subtitle: "Movies & TV"
        tag: "app"
        keywords: "media"
        url: "https://jellyfin.danteb.com"
        target: "_blank" # optional html a tag target attribute
      - name: "Overseerr"
        logo: "assets/homer-icons/svg/overseerr.svg"
        subtitle: "Request Content"
        tag: "app"
        keywords: "request media"
        url: "https://overseerr.danteb.com"
        target: "_blank" # optional html a tag target attribute
      - name: "Immich"
        logo: "assets/homer-icons/svg/immich.svg"
        subtitle: "Photos"
        tag: "app"
        keywords: "media photos"
        url: "https://immich.danteb.com"
        target: "_blank" # optional html a tag target attribute
  - name: "Utilities"
    icon: "fas fa-gears"
    items:
      - name: "Authelia"
        logo: "assets/homer-icons/svg/authelia.svg"
        subtitle: "Two-Factor Authentication"
        tag: "app"
        keywords: "security"
        url: "https://authelia.danteb.com"
        target: "_blank" # optional html a tag target attribute
      - name: "Dashdot"
        logo: "assets/tools/dashdot_logo.png"
        subtitle: "Server status"
        tag: "app"
        keywords: "monitoring"
        url: "https://dashdot.danteb.com"
        target: "_blank" # optional html a tag target attribute
      - name: "Vaultwarden"
        logo: "assets/homer-icons/png/vaultwarden.png"
        subtitle: "Password Manager"
        tag: "app"
        keywords: "utilities password bitwarden"
        url: "https://vaultwarden.danteb.com"
        target: "_blank" # optional html a tag target attribute
      - name: "Komga"
        logo: "assets/homer-icons/png/komga.png"
        subtitle: "Reader"
        tag: "app"
        keywords: "manga manhwa manhua ebooks e-books"
        url: "https://komga.danteb.com"
        target: "_blank" # optional html a tag target attribute
  - name: "Downloads"
    icon: "fas fa-download"
    items:
      - name: "qBittorrent"
        logo: "assets/homer-icons/svg/qbittorrent.svg"
        subtitle: "Torrents"
        tag: "app"
        keywords: "p2p"
        url: "https://qbittorrent.danteb.com"
        target: "_blank" # optional html a tag target attribute
      - name: "SABnzbd"
        logo: "assets/homer-icons/svg/sabnzbd.svg"
        subtitle: "NZB"
        tag: "app"
        keywords: "p2p"
        url: "https://sabnzbd.danteb.com"
        target: "_blank" # optional html a tag target attribute
      - name: "Suwayomi"
        logo: "assets/tools/suwayomi_logo.png"
        subtitle: "Manga & WebToons"
        tag: "app"
        keywords: "mihon tachiyomi manga manhwa manhua"
        url: "https://suwayomi.danteb.com/"
        target: "_blank" # optional html a tag target attribute
      - name: "SearXNG"
        logo: "assets/homer-icons/png/searxmetasearchengine.png"
        subtitle: "Metasearch Engine"
        tag: "app"
        keywords: "utilities search searx"
        url: "https://searxng.danteb.com"
        target: "_blank" # optional html a tag target attribute
  - name: "Starr"
    icon: "fas fa-star"
    items:
      - name: "Radarr"
        logo: "assets/homer-icons/svg/radarr.svg"
        subtitle: "Movies"
        tag: "app"
        keywords: "p2p"
        url: "https://radarr.danteb.com"
        target: "_blank" # optional html a tag target attribute
      - name: "Sonarr"
        logo: "assets/homer-icons/svg/sonarr.svg"
        subtitle: "TV"
        tag: "app"
        keywords: "p2p"
        url: "https://sonarr.danteb.com"
        target: "_blank" # optional html a tag target attribute
      - name: "Bazarr"
        logo: "assets/homer-icons/svg/bazarr.svg"
        subtitle: "Subtitles"
        tag: "app"
        keywords: "p2p"
        url: "https://bazarr.danteb.com"
        target: "_blank" # optional html a tag target attribute
      - name: "Prowlarr"
        logo: "assets/homer-icons/svg/prowlarr.svg"
        subtitle: "Indexer"
        tag: "app"
        keywords: "p2p"
        url: "https://prowlarr.danteb.com"
        target: "_blank" # optional html a tag target attribute
  - name: "Networking"
    icon: "fas fa-network-wired"
    items:
      # - name: "Adguard Home"
      #   logo: "assets/homer-icons/svg/adguardhome.svg"
      #   subtitle: "Ad-Blocking DNS & DHCP"
      #   tag: "app"
      #   keywords: "network"
      #   url: "https://adguard.danteb.com"
      #   target: "_blank" # optional html a tag target attribute
      - name: "Nginx Proxy Manager"
        logo: "assets/homer-icons/png/nginxproxymanager.png"
        subtitle: "Reverse Proxy"
        tag: "app"
        keywords: "media"
        url: "https://nginx-proxy-manager.danteb.com"
        target: "_blank" # optional html a tag target attribute
